#!/system/bin/sh
# ==============================================================================
# Interactive Setup Wizard for Nothing Essential Sync
# Works directly in Termux, Root Shell, or via ADB
# ==============================================================================

set -u

BASE_DIR="/data/adb/essential-sync"
CONFIG_FILE="${BASE_DIR}/config.env"
STATE_FILE="${BASE_DIR}/last_sync_time.txt"

clear 2>/dev/null || true
echo "=========================================================="
echo "  Nothing Essential Space -> Obsidian Kurulum Sihirbazı"
echo "=========================================================="
echo ""

# 1. Obsidian Kasalarını Otomatik Tara
echo "🔍 Cihazdaki Obsidian kasaları taranıyor..."
VAULTS=""
COUNT=0

# Yaygın Obsidian konumlarını tara
FOUND_VAULTS=$(find /storage/emulated/0 -maxdepth 5 -type d -name ".obsidian" 2>/dev/null)

if [ -n "${FOUND_VAULTS}" ]; then
    echo "Bulunan Obsidian Kasaları:"
    echo "${FOUND_VAULTS}" | while read -r line; do
        COUNT=$((COUNT + 1))
        VAULT_DIR=$(dirname "$line")
        VAULT_NAME=$(basename "$VAULT_DIR")
        echo "  [${COUNT}] ${VAULT_NAME} (${VAULT_DIR})"
    done
    TOTAL_FOUND=$(echo "${FOUND_VAULTS}" | wc -l)
    CUSTOM_OPTION=$((TOTAL_FOUND + 1))
    echo "  [${CUSTOM_OPTION}] Farklı / Özel bir klasör yolu girin"
    echo ""
    printf "Seçiminiz [1-%s]: " "${CUSTOM_OPTION}"
    read -r CHOICE
else
    CHOICE="manual"
fi

SELECTED_VAULT=""
if [ "${CHOICE}" != "manual" ] && [ -n "${FOUND_VAULTS}" ]; then
    case "${CHOICE}" in
        ''|*[!0-9]*) SELECTED_VAULT="" ;;
        *)
            if [ "${CHOICE}" -ge 1 ] 2>/dev/null && [ "${CHOICE}" -le "${TOTAL_FOUND}" ] 2>/dev/null; then
                SELECTED_LINE=$(echo "${FOUND_VAULTS}" | sed -n "${CHOICE}p")
                SELECTED_VAULT=$(dirname "${SELECTED_LINE}")
            fi
            ;;
    esac
fi

if [ -z "${SELECTED_VAULT}" ]; then
    echo ""
    printf "Lütfen hedef not klasörünün tam yolunu girin: "
    read -r SELECTED_VAULT
fi

if [ -z "${SELECTED_VAULT}" ]; then
    SELECTED_VAULT="/storage/emulated/0/Documents/EssentialNotes"
fi

# 2. Not ve Ekler Klasörlerini Belirle
DEFAULT_NOTES_DIR="${SELECTED_VAULT}/00-Zettelkasten"
DEFAULT_ATTACHMENTS_DIR="${SELECTED_VAULT}/99-index/Files"

# Eğer app.json varsa oku
APP_JSON="${SELECTED_VAULT}/.obsidian/app.json"
if [ -f "${APP_JSON}" ]; then
    DETECTED_ATT=$(grep -o '"attachmentFolderPath"[^,]*' "${APP_JSON}" 2>/dev/null | cut -d':' -f2 | tr -d ' "\r\n')
    if [ -n "${DETECTED_ATT}" ]; then
        DEFAULT_ATTACHMENTS_DIR="${SELECTED_VAULT}/${DETECTED_ATT}"
    fi
    DETECTED_FOLDER=$(grep -o '"newFileFolderPath"[^,]*' "${APP_JSON}" 2>/dev/null | cut -d':' -f2 | tr -d ' "\r\n')
    if [ -n "${DETECTED_FOLDER}" ]; then
        DEFAULT_NOTES_DIR="${SELECTED_VAULT}/${DETECTED_FOLDER}"
    fi
fi

echo ""
echo "📁 Notlar nereye kaydedilsin?"
printf "Varsayılan [%s]: " "${DEFAULT_NOTES_DIR}"
read -r INPUT_NOTES
DEST_NOTES="${INPUT_NOTES:-${DEFAULT_NOTES_DIR}}"

echo ""
echo "📎 Görseller ve ses kayıtları nereye kaydedilsin?"
printf "Varsayılan [%s]: " "${DEFAULT_ATTACHMENTS_DIR}"
read -r INPUT_ATT
DEST_ATTACHMENTS="${INPUT_ATT:-${DEFAULT_ATTACHMENTS_DIR}}"

# 3. Dosya Adı Zaman Formatı
echo ""
echo "🕒 Dosya adındaki tarih/saat formatı:"
echo "  [1] YYYY-MM-DD HH.mm (Örn: 2026-10-06 14.30 - Başlık.md - Önerilen)"
echo "  [2] YYYY-MM-DD-HHmm  (Örn: 2026-10-06-1430 - Başlık.md)"
echo "  [3] Sadece Tarih     (Örn: 2026-10-06 - Başlık.md)"
printf "Seçiminiz [1]: "
read -r TIME_CHOICE
case "${TIME_CHOICE}" in
    2) TIME_FORMAT="%Y-%m-%d-%H%M" ;;
    3) TIME_FORMAT="%Y-%m-%d" ;;
    *) TIME_FORMAT="%Y-%m-%d %H.%M" ;;
esac

# 4. Frontmatter Etiketi
echo ""
printf "🏷️  Varsayılan not etiketi [inbox/essential-space]: "
read -r INPUT_TAG
NOTE_TAG="${INPUT_TAG:-inbox/essential-space}"

# 5. Geçmiş Notlar Tercihi
echo ""
printf "🔄 Essential Space'teki mevcut geçmiş notlar da aktarılsın mı? [E/h]: "
read -r SYNC_PAST_CHOICE
case "${SYNC_PAST_CHOICE}" in
    [hH]*)
        # Sadece şimdiden sonrakileri al
        NOW_MS=$(date +%s000 2>/dev/null || echo "1790000000000")
        echo "${NOW_MS}" > "${STATE_FILE}"
        echo "✓ Sadece bundan sonra alınacak yeni notlar senkronize edilecek."
        ;;
    *)
        echo "0" > "${STATE_FILE}"
        echo "✓ Mevcut tüm geçmiş notlar ilk senkronizasyonda aktarılacak."
        ;;
esac

# 6. config.env Dosyasını Yaz
DEST_NOTES=$(echo "${DEST_NOTES}" | tr -d '"`$\r\n')
DEST_ATTACHMENTS=$(echo "${DEST_ATTACHMENTS}" | tr -d '"`$\r\n')
TIME_FORMAT=$(echo "${TIME_FORMAT}" | tr -d '"`$\r\n')
NOTE_TAG=$(echo "${NOTE_TAG}" | tr -d '"`$\r\n')

mkdir -p "${BASE_DIR}" "${DEST_NOTES}" "${DEST_ATTACHMENTS}" 2>/dev/null

cat <<EOF > "${CONFIG_FILE}"
# ==============================================================================
# Nothing Essential Space -> Obsidian Sync Configuration
# Generated by setup.sh on $(date '+%Y-%m-%d %H:%M:%S')
# ==============================================================================

DEST_NOTES="${DEST_NOTES}"
DEST_ATTACHMENTS="${DEST_ATTACHMENTS}"
TIME_FORMAT="${TIME_FORMAT}"
NOTE_TAG="${NOTE_TAG}"
EOF

chmod 644 "${CONFIG_FILE}" 2>/dev/null

echo ""
echo "=========================================================="
echo "✓ Yapılandırma başarıyla kaydedildi!"
echo "  Not Yolu: ${DEST_NOTES}"
echo "  Ekler Yolu: ${DEST_ATTACHMENTS}"
echo "  Format: ${TIME_FORMAT}"
echo "  Etiket: #${NOTE_TAG}"
echo "=========================================================="
echo ""
printf "Şimdi ilk senkronizasyonu başlatmak ister misiniz? [E/h]: "
read -r RUN_NOW
case "${RUN_NOW}" in
    [hH]*)
        echo "Kurulum tamamlandı. Arka plan servisi çalışmaya devam ediyor."
        ;;
    *)
        echo "Senkronizasyon çalıştırılıyor..."
        sh "${BASE_DIR}/sync.sh"
        ;;
esac
